# Generated by Django 2.1.7 on 2019-04-01 22:26

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resumecv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationSectionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('dates', models.CharField(max_length=50)),
                ('company_location', models.CharField(blank=True, max_length=250)),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_item', to='resumecv.ResumePage')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceSectionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('dates', models.CharField(max_length=50)),
                ('company_location', models.CharField(blank=True, max_length=250)),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_item', to='resumecv.ResumePage')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('percent', models.CharField(default='100%', max_length=4)),
            ],
            options={
                'verbose_name_plural': 'personal skills percentages',
            },
        ),
        migrations.CreateModel(
            name='TechnicalSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('percent', models.CharField(default='100%', max_length=4)),
            ],
            options={
                'verbose_name_plural': 'technical skills percentages',
            },
        ),
        migrations.AddField(
            model_name='resumepage',
            name='PersonalSkills',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='resumecv.PersonalSkills'),
        ),
        migrations.AddField(
            model_name='resumepage',
            name='TechnicalSkills',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='resumecv.TechnicalSkills'),
        ),
    ]
