# Generated by Django 2.1.7 on 2019-04-01 22:30

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resumecv', '0002_auto_20190401_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationsectionitem',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_item', to='resumecv.ResumePage'),
        ),
        migrations.AlterField(
            model_name='experiencesectionitem',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_item', to='resumecv.ResumePage'),
        ),
    ]
