# Generated by Django 2.1.7 on 2019-04-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumecv', '0003_auto_20190401_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationsectionitem',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='experiencesectionitem',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
