# Generated by Django 2.1.7 on 2019-04-01 22:50

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resumecv', '0004_auto_20190401_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationsectionitem',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='experiencesectionitem',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=100),
        ),
    ]
