# Generated by Django 2.1.7 on 2019-04-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumecv', '0005_auto_20190401_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumepage',
            name='heading',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
