# Generated by Django 2.1.7 on 2019-04-04 22:08

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resumecv', '0006_auto_20190401_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationsectionitem',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experiencesectionitem',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
