# Generated by Django 2.1.7 on 2019-03-31 19:00

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190329_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpagegalleryimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='blog.BlogIndexPage'),
        ),
    ]
