# Generated by Django 2.1.7 on 2019-03-30 20:19

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0011_lefthighlightssection_righthighlightssection'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftBullet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bullet', models.CharField(max_length=50)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_section_bullet', to='home.HomePage')),
            ],
        ),
        migrations.CreateModel(
            name='LeftHighlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_section_header', to='home.HomePage')),
            ],
        ),
        migrations.CreateModel(
            name='RightBullet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bullet', models.CharField(max_length=50)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_section_bullet', to='home.HomePage')),
            ],
        ),
        migrations.CreateModel(
            name='RightHighlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_section_header', to='home.HomePage')),
            ],
        ),
        migrations.RemoveField(
            model_name='lefthighlightssection',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='lefthighlightssection',
            name='page',
        ),
        migrations.RemoveField(
            model_name='righthighlightssection',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='righthighlightssection',
            name='page',
        ),
        migrations.DeleteModel(
            name='LeftHighlightsSection',
        ),
        migrations.DeleteModel(
            name='RightHighlightsSection',
        ),
    ]
