# Generated by Django 2.1.7 on 2019-03-30 21:44

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190330_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leftbullet',
            name='bullet',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leftbullet',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_highlight_bullet', to='home.HomePage'),
        ),
        migrations.AlterField(
            model_name='lefthighlight',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_highlight', to='home.HomePage'),
        ),
        migrations.AlterField(
            model_name='rightbullet',
            name='bullet',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rightbullet',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_highlight_bullet', to='home.HomePage'),
        ),
        migrations.AlterField(
            model_name='righthighlight',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_highlight', to='home.HomePage'),
        ),
    ]
