# Generated by Django 2.1.7 on 2019-03-31 19:00

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0014_auto_20190331_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.CharField(max_length=255)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name_plural': 'fun facts',
            },
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='fun_fact',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.FunFact'),
        ),
    ]
