# Generated by Django 2.1.7 on 2019-04-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20190402_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leftbullet',
            name='bullet',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rightbullet',
            name='bullet',
            field=models.CharField(max_length=200),
        ),
    ]
