# Generated by Django 2.1.7 on 2019-04-04 19:17

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20190404_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
