# Generated by Django 2.1.7 on 2019-03-27 14:53

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='project.ProjectCategory'),
        ),
    ]
