# Generated by Django 2.1.7 on 2019-03-28 19:25

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projectpage_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpage',
            old_name='body',
            new_name='description',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='outcome',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='intro',
            field=models.CharField(max_length=300),
        ),
    ]
