# Generated by Django 2.1.7 on 2019-03-28 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20190328_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='url',
        ),
    ]
