# Generated by Django 2.1.7 on 2019-03-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_projectpage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='url',
            field=models.URLField(default='www.insert_link_to_project_here.com'),
            preserve_default=False,
        ),
    ]
