# Generated by Django 2.1.7 on 2019-03-28 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_projectpage_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='url',
        ),
    ]
